#!/bin/sh
### BEGIN INIT INFO
# Provides:          lcd_print_ip
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:     
# Short-Description: Print IP on LCD
### END INIT INFO

PATH=$PATH:/usr/bin:/usr/local/bin

COUNT=0
SLEEPSECONDS=1
MAXTRIES=20

if [ ${1} = "start" ]; then
    IP=$(hostname -I)

    while [ ${#IP} -eq 0 ]; do
	COUNT=$((${COUNT}+1))
        if [ ${COUNT} -ge ${MAXTRIES} ]; then
            break
        fi
        sleep ${SLEEPSECONDS} 
        IP=$(hostname -I)
    done

    if [ ${#IP} -eq 0 ]; then
        lcd -1 $(hostname) -2 "No IP :-("
    else
        lcd -1 $(hostname) -2 "${IP}"
    fi
fi
